### ISSUE TITLE
srs-sip可以和上级国标平台级联吗？

### ISSUE THREAD

**Issue by yy-ma** [ossrs/srs-sip#2]
srs-sip可以和上级国标平台级联吗？

1.两个srs-sip是否可以级联？
2.srs-sip和其他国标平台是否可以级联？如：[WVP平台](https://github.com/648540858/wvp-GB28181-pro)，上级或下级

**Comment by stormbirds** [comment]
> 

暂时没有实现国标级联功能，只实现了基本的SIP注册、拉流播放、心跳等基本功能
